apiVersion: v1
kind: Pod
metadata:
  name: toleration-demo
  namespace: production
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "environment"
      operator: "Equal"
      value: "prod"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: <your-node-name>
