apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: production
spec:
  containers:
  - name: app
    image: nginx
    envFrom:
    - configMapRef:
        name: my-config
    - secretRef:
        name: my-secret
