apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: production
type: Opaque
data:
  DB_USER: YWRtaW4=        # base64 encoded "admin"
  DB_PASSWORD: c2VjcmV0    # base64 encoded "secret"
